In [1]:
import torch

In [2]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [3]:
# get first example by index
print(x[0].shape)
print(x[0 , :].shape)

torch.Size([25])
torch.Size([25])


In [4]:
# get first feature by index
print(x[:, 0].shape)

torch.Size([10])


In [5]:
# get first 10 features of third example
print(x[2, 0:10].shape)

torch.Size([10])


In [6]:
# fancy indexing
x = torch.arange(5,15,1)
indices = [2, 5, 8]
print(x[indices])

tensor([ 7, 10, 13])


In [7]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols])

tensor([0.2830, 0.6380])


In [8]:
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])

tensor([0, 1, 9])


In [9]:
print(x[x.remainder(2) == 0])
print(torch.where(x > 5, x, x*2))
print(torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())
print(x.ndimension())

tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1


In [10]:
print(x.numel())

10
