In [1]:
import torch

In [24]:
gen = torch.Generator().manual_seed(2562)
random_tensor = torch.rand(10, generator=gen)
random_tensor

tensor([0.4127, 0.3956, 0.8160, 0.1514, 0.3352, 0.8242, 0.3449, 0.0019, 0.4804,
        0.9624])

In [43]:
random_tensor_probabs = random_tensor / random_tensor.sum()
random_tensor_probabs

tensor([0.0874, 0.0837, 0.1727, 0.0320, 0.0709, 0.1744, 0.0730, 0.0004, 0.1017,
        0.2037])

In [47]:
torch.multinomial(random_tensor_probabs, 50, replacement=True, generator=gen)

tensor([0, 9, 4, 8, 8, 8, 9, 5, 2, 4, 2, 9, 9, 2, 2, 5, 9, 0, 5, 0, 0, 1, 2, 5,
        9, 8, 2, 5, 1, 8, 4, 5, 5, 5, 9, 1, 9, 6, 2, 1, 1, 6, 6, 6, 9, 0, 0, 1,
        9, 9])