In [1]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

In [3]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)
print(x_3x3)
print(x_3x3.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])


In [4]:
x_3x3 = x.reshape(3, 3)
print(x_3x3)
print(x_3x3.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])


In [5]:
y = x_3x3.t()
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [6]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [7]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [8]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [9]:
z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 5, 2])


In [11]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [12]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

torch.Size([1, 1, 10])


In [13]:
z = x.squeeze(1)
print(z.shape)

torch.Size([1, 10])
