In [1]:
import torch
import numpy as np

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

## Specific Value Initialization

In [3]:
a = torch.tensor([[1,2,3],
                  [4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
a = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.float32, device=device)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [5]:
a = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

### Exploring Tensor Properties

In [6]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [7]:
a.dtype

torch.float32

In [8]:
a.device

device(type='cuda', index=0)

In [9]:
a.shape

torch.Size([2, 3])

In [10]:
a.requires_grad

True

## Empty Initialization

In [11]:
b = torch.empty(size = (3,3), device=device, requires_grad=True)
b

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)

In [12]:
b = torch.empty(size = (3,3), device=device).normal_(mean=0, std=1)
b

tensor([[-0.3670,  0.6681,  0.1981],
        [ 1.0514, -0.5233, -0.3773],
        [ 0.1569,  0.6732,  0.2033]], device='cuda:0')

In [13]:
b = torch.empty(size = (3,3), device=device).uniform_(0,1)
b

tensor([[0.0349, 0.3871, 0.6026],
        [0.4891, 0.1019, 0.3250],
        [0.6118, 0.9450, 0.4307]], device='cuda:0')

## Zero Initialization

In [14]:
c = torch.zeros((3,3))
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
c = torch.zeros(size=(3,3), dtype=torch.float32, device=device, requires_grad=True)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)

### Random Initialization

In [16]:
d = torch.rand((3,3))
d

tensor([[0.9800, 0.3576, 0.7161],
        [0.1384, 0.6028, 0.4443],
        [0.6047, 0.0436, 0.5746]])

## Ones Initialization

In [17]:
e = torch.ones((3,3))
e

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Identity Matrix Initialization

In [18]:
f = torch.eye(3)
f

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
f = torch.eye(5,5)
f

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Array range Initialization

In [20]:
g = torch.arange(start=0, end=5, step=1)
g

tensor([0, 1, 2, 3, 4])

## Linear Initialization

In [21]:
h = torch.linspace(start=0.1, end=1, steps=20)
h

tensor([0.1000, 0.1474, 0.1947, 0.2421, 0.2895, 0.3368, 0.3842, 0.4316, 0.4789,
        0.5263, 0.5737, 0.6211, 0.6684, 0.7158, 0.7632, 0.8105, 0.8579, 0.9053,
        0.9526, 1.0000])

## Convert Tensors to Types

In [22]:
i = torch.arange(start=0, end=5, step=1)
i

tensor([0, 1, 2, 3, 4])

In [23]:
bool_i = i.bool()
bool_i

tensor([False,  True,  True,  True,  True])

In [24]:
print(i.dtype)
print(bool_i.dtype)

torch.int64
torch.bool


In [25]:
print(i.short().dtype)
print(i.long().dtype)
print(i.half().dtype)
print(i.float().dtype)
print(i.double().dtype)

torch.int16
torch.int64
torch.float16
torch.float32
torch.float64


## NumPy to Tensor Conversion

In [26]:
np_array = np.zeros((5,5))
j = torch.from_numpy(np_array)
np_array_from_torch = j.numpy()
print(np_array, j, np_array_from_torch, sep='\n')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
