In [1]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

## Addition

In [2]:
a = torch.tensor([1,2,3], device=device)
b = torch.tensor([9,8,7], device=device)

In [3]:
z1 = torch.empty(3, device=device)
torch.add(a,b, out=z1)
print(z1)

tensor([10., 10., 10.], device='cuda:0')


In [4]:
z2 = torch.add(a,b)
print(z2)

tensor([10, 10, 10], device='cuda:0')


In [5]:
z = a + b
print(z)

tensor([10, 10, 10], device='cuda:0')


## Subtraction

In [7]:
z = a - b
print(z)

tensor([-8, -6, -4], device='cuda:0')


## Division

In [9]:
z = torch.true_divide(a,b)
print(z)

tensor([0.1111, 0.2500, 0.4286], device='cuda:0')


In [10]:
z = torch.true_divide(a,2)
print(z)  

tensor([0.5000, 1.0000, 1.5000], device='cuda:0')


## Inplace Operations

### Addition

In [11]:
t = torch.zeros(3, device=device)
t.add_(a)
print(t)

tensor([1., 2., 3.], device='cuda:0')


In [12]:
t += a
print(t)

tensor([2., 4., 6.], device='cuda:0')


### Exponentiation

In [15]:
z = a.pow(2)
print(z)

tensor([1, 4, 9], device='cuda:0')


In [16]:
z = a ** 2
print(z)

tensor([1, 4, 9], device='cuda:0')


## Comparison

In [17]:
z = a > 0
print(z)
z = b < 8
print(z)

tensor([True, True, True], device='cuda:0')
tensor([False, False,  True], device='cuda:0')


## Matrix Multiplication

In [19]:
x1 = torch.rand((2, 5), device=device)
x2 = torch.rand((5, 3), device=device)
x3 = torch.mm(x1, x2)
print(x3)

tensor([[1.7483, 1.6754, 1.5162],
        [2.2592, 2.0757, 2.2657]], device='cuda:0')


In [20]:
x3 = x1.mm(x2)
print(x3)

tensor([[1.7483, 1.6754, 1.5162],
        [2.2592, 2.0757, 2.2657]], device='cuda:0')


## Matrix Exponentiation

In [21]:
x1 = torch.rand((5, 5), device=device)
x1.matrix_power(3)

tensor([[ 3.9080,  5.2670,  5.3657,  4.1427,  6.1921],
        [ 8.2586,  9.6921,  9.3977,  7.9180, 11.4653],
        [ 5.4499,  6.2769,  5.8783,  5.2064,  7.2157],
        [ 7.1776,  8.7997,  8.7041,  7.0922, 10.3246],
        [ 7.8472,  9.0404,  8.6604,  7.4194, 10.5562]], device='cuda:0')

## Element wise Multiplication

In [22]:
z = a * b
print(z)

tensor([ 9, 16, 21], device='cuda:0')


## Dot Product

In [28]:
z = torch.dot(a.float(),b.float())
print(z)

tensor(46., device='cuda:0')


## Batch Matrix Multiplication

In [29]:
batch = 32
n = 10
m = 20
p = 30

In [31]:
t1 = torch.rand((batch, n, m), device=device)
t2 = torch.rand((batch, m, p), device=device)
out_bmm = torch.bmm(t1, t2)
print(out_bmm.shape)

torch.Size([32, 10, 30])


## Broadcasting

In [40]:
x1 = torch.rand((5, 5), device=device)
x2 = torch.rand((1, 5), device=device)
# x2 = torch.rand((5, 1), device=device)

In [41]:
z = x1 - x2
print(z)

tensor([[ 0.3750,  0.1763, -0.2414, -0.4573,  0.3959],
        [ 0.1116,  0.0288, -0.1623,  0.1675,  0.3319],
        [ 0.2257, -0.2893, -0.6766, -0.4745, -0.0739],
        [-0.0114,  0.1002,  0.0643, -0.3117, -0.2415],
        [ 0.6009, -0.0583, -0.5924, -0.5132,  0.6164]], device='cuda:0')


## Other Operation

In [44]:
sum_a = torch.sum(a, dim=0)
sum_a

tensor(6, device='cuda:0')

In [46]:
values, indices = torch.max(a, dim=0)
values, indices

(tensor(3, device='cuda:0'), tensor(2, device='cuda:0'))

In [47]:
abs_a = torch.abs(a)
abs_a

tensor([1, 2, 3], device='cuda:0')

In [48]:
z = torch.argmax(a, dim=0)
z

tensor(2, device='cuda:0')

In [50]:
mean_a = torch.mean(a.float(), dim=0)
mean_a

tensor(2., device='cuda:0')

In [51]:
z = torch.eq(a, b)
z

tensor([False, False, False], device='cuda:0')

In [53]:
sorted_b, indices = torch.sort(b, dim=0, descending=False)
sorted_b, indices

(tensor([7, 8, 9], device='cuda:0'), tensor([2, 1, 0], device='cuda:0'))

In [54]:
z = torch.clamp(a, min=2)
z

tensor([2, 2, 3], device='cuda:0')

In [55]:
z = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(z)
z

tensor(True)

In [56]:
z = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.all(z)
z

tensor(False)