In [1]:
import torch

In [2]:
a = torch.randn(5, 3, 4)

In [3]:
a

tensor([[[-0.5509,  0.3951, -1.3916,  1.4671],
         [-0.5162,  0.7995, -1.2033, -0.2200],
         [ 0.2676,  0.4060,  0.3190,  0.1713]],

        [[-1.9916,  1.4774,  0.9488, -0.5068],
         [ 1.0864, -0.1612,  0.2118, -0.8164],
         [ 0.1097, -0.2565, -1.1209, -0.7171]],

        [[-1.4192,  0.4893,  1.1025, -1.0740],
         [ 0.4817,  0.2108, -1.9883,  0.0739],
         [ 0.4283, -0.1387,  0.6473, -0.5164]],

        [[-0.0648, -0.4483, -0.1330, -0.3789],
         [-0.8601, -0.1628, -0.1552,  0.9631],
         [-0.5872, -0.4752,  0.9242, -0.9560]],

        [[ 1.4404, -0.7885,  1.0787,  0.1287],
         [ 1.7875, -0.8570, -2.5231,  0.3951],
         [ 1.2405, -0.6490,  0.3041, -0.7276]]])

In [32]:
# 5 matrices, 3 rows, 4 columns
a.shape


torch.Size([5, 3, 4])

In [21]:
print(a.sum(dim=0))
print(a.sum(dim=0).shape)

tensor([[-2.5861,  1.1251,  1.6055, -0.3638],
        [ 1.9794, -0.1707, -5.6581,  0.3957],
        [ 1.4589, -1.1134,  1.0737, -2.7458]])
torch.Size([3, 4])


In [22]:
print(a.sum(dim=1))
print(a.sum(dim=1).shape)

tensor([[-0.7995,  1.6006, -2.2759,  1.4183],
        [-0.7955,  1.0597,  0.0397, -2.0403],
        [-0.5092,  0.5614, -0.2385, -1.5165],
        [-1.5122, -1.0862,  0.6360, -0.3717],
        [ 4.4684, -2.2945, -1.1402, -0.2038]])
torch.Size([5, 4])


In [23]:
print(a.sum(dim=2))
print(a.sum(dim=2).shape)

tensor([[-0.0802, -1.1400,  1.1639],
        [-0.0722,  0.3206, -1.9848],
        [-0.9013, -1.2218,  0.4205],
        [-1.0249, -0.2150, -1.0942],
        [ 1.8594, -1.1975,  0.1681]])
torch.Size([5, 3])


In [25]:
print(a.sum(dim=0, keepdim=True))
print(a.sum(dim=0, keepdim=True).shape)

tensor([[[-2.5861,  1.1251,  1.6055, -0.3638],
         [ 1.9794, -0.1707, -5.6581,  0.3957],
         [ 1.4589, -1.1134,  1.0737, -2.7458]]])
torch.Size([1, 3, 4])


In [26]:
print(a.sum(dim=1, keepdim=True))
print(a.sum(dim=1, keepdim=True).shape)

tensor([[[-0.7995,  1.6006, -2.2759,  1.4183]],

        [[-0.7955,  1.0597,  0.0397, -2.0403]],

        [[-0.5092,  0.5614, -0.2385, -1.5165]],

        [[-1.5122, -1.0862,  0.6360, -0.3717]],

        [[ 4.4684, -2.2945, -1.1402, -0.2038]]])
torch.Size([5, 1, 4])


In [27]:
print(a.sum(dim=2, keepdim=True))
print(a.sum(dim=2, keepdim=True).shape)

tensor([[[-0.0802],
         [-1.1400],
         [ 1.1639]],

        [[-0.0722],
         [ 0.3206],
         [-1.9848]],

        [[-0.9013],
         [-1.2218],
         [ 0.4205]],

        [[-1.0249],
         [-0.2150],
         [-1.0942]],

        [[ 1.8594],
         [-1.1975],
         [ 0.1681]]])
torch.Size([5, 3, 1])


In [13]:
b = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

In [16]:
b.shape

torch.Size([2, 5])

In [28]:
print(b.sum(dim=0))
print(b.sum(dim=0).shape)

tensor([ 7,  9, 11, 13, 15])
torch.Size([5])


In [29]:
print(b.sum(dim=1))
print(b.sum(dim=1).shape)

tensor([15, 40])
torch.Size([2])


In [30]:
print(b.sum(dim=0, keepdim=True))
print(b.sum(dim=0, keepdim=True).shape)

tensor([[ 7,  9, 11, 13, 15]])
torch.Size([1, 5])


In [31]:
print(b.sum(dim=1, keepdim=True))
print(b.sum(dim=1, keepdim=True).shape)

tensor([[15],
        [40]])
torch.Size([2, 1])
