In [95]:
import torch

In [96]:
text_sequence = torch.LongTensor([[1, 2, 3, 4, 5, 6, 7],[1, 2, 3, 4, 5, 6, 7]])

In [97]:
text_sequence

tensor([[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]])

In [98]:
vocab_size = 10
embedding_dim = 3
embedding_layer = torch.nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

In [99]:
embeddings = embedding_layer(text_sequence)

In [100]:
embeddings.shape

torch.Size([2, 7, 3])

In [101]:
embeddings.view(2, -1, 3).shape # batch_size, sequence_length, embedding_dim

torch.Size([2, 7, 3])

In [106]:
num_layers = 2
batch_size = 2
hidden_size = 5
hidden = torch.zeros(num_layers, batch_size, hidden_size)
rnn_layer = torch.nn.RNN(input_size=3, hidden_size=hidden_size, batch_first=True, num_layers=num_layers, bias=False)

In [107]:
hidden

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [108]:
out, hidden = rnn_layer(embeddings.view(2, -1, 3), hidden)
out


tensor([[[-0.1585, -0.1057, -0.0623,  0.0574, -0.0072],
         [ 0.0988,  0.1643,  0.0838,  0.0683, -0.3297],
         [ 0.2076,  0.3346,  0.3153, -0.1710, -0.2642],
         [ 0.0518,  0.2112,  0.3727,  0.0225, -0.5084],
         [-0.6566, -0.1635, -0.4729,  0.0502, -0.2645],
         [ 0.3646,  0.2275, -0.0118, -0.3770, -0.0481],
         [-0.2796,  0.0548, -0.0805,  0.1433, -0.0453]],

        [[-0.1585, -0.1057, -0.0623,  0.0574, -0.0072],
         [ 0.0988,  0.1643,  0.0838,  0.0683, -0.3297],
         [ 0.2076,  0.3346,  0.3153, -0.1710, -0.2642],
         [ 0.0518,  0.2112,  0.3727,  0.0225, -0.5084],
         [-0.6566, -0.1635, -0.4729,  0.0502, -0.2645],
         [ 0.3646,  0.2275, -0.0118, -0.3770, -0.0481],
         [-0.2796,  0.0548, -0.0805,  0.1433, -0.0453]]],
       grad_fn=<TransposeBackward1>)

In [109]:
out.reshape(out.shape[0], -1).shape

torch.Size([2, 35])