In [1]:
import torch

In [3]:
logits = torch.tensor([-100, -1, 3 , 10])
exponentials = torch.exp(logits)
probabilities = exponentials / torch.sum(exponentials)
probabilities

tensor([0.0000e+00, 1.6686e-05, 9.1104e-04, 9.9907e-01])

In [6]:
logits = torch.tensor([-100, -1, 3 , 10]) - 10
exponentials = torch.exp(logits)
probabilities = exponentials / torch.sum(exponentials)
probabilities

tensor([0.0000e+00, 1.6686e-05, 9.1104e-04, 9.9907e-01])

In [4]:
logits = torch.tensor([-100, -1, 3 , 100])
exponentials = torch.exp(logits)
probabilities = exponentials / torch.sum(exponentials)
probabilities

tensor([0., 0., 0., nan])

In [5]:
logits = torch.tensor([-100, -1, 3 , 100]) - 100
exponentials = torch.exp(logits)
probabilities = exponentials / torch.sum(exponentials)
probabilities

tensor([0.0000e+00, 1.4013e-44, 7.4689e-43, 1.0000e+00])